---

- name: Workstation Setup (Ubuntu)
  hosts: 127.0.0.1
  connection: local
  user: "{{ workstation_user }}"
  become: yes
  roles:
    - general
    - cleanup
    - go
    - virtualization
    - php
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal-console
    - role: nodejs
      nvm_version: v0.33.2
