---
- name: Copy .gitconfig to user home.
  copy:
    src: .gitconfig
    dest: /home/{{ ansible_ssh_user }}/.gitconfig
    mode: 0664
    owner: "{{ ansible_ssh_user }}"

- name: Copy global .gitignore to user home.
  copy:
    src: .gitignore
    dest: /home/{{ ansible_ssh_user }}/.gitignore
    mode: 0664
    owner: "{{ ansible_ssh_user }}"
