---
- name: Download Tomorrow theme.
  get_url:
    url: https://raw.githubusercontent.com/chriskempson/tomorrow-theme/master/Gnome-Terminal/setup-theme.sh
    dest: /tmp/setup-theme.sh
    mode: a+x

- name: Install Tomorrow theme.
  shell: /tmp/setup-theme.sh Tomorrow-Night-Bright

- name: Remove Tomorrow theme installation files.
  file:
    path: /tmp/setup-theme.sh
    state: absent
