---

- name: Configure the Oracle APT key
  become: yes
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: Add Virtualbox repository.
  become: yes
  shell: apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib"

- name: Add Virtualbox key.
  become: yes
  apt_key:
    url: "http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc"
    state: present

- name: Add Virtualbox year key.
  become: yes
  apt_key:
    url: "http://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc"
    state: present

- name: Install Virtualbox.
  become: yes
  apt:
    name: virtualbox-5.1
    state: present
    update_cache: yes

- name: Install Vagrant.
  become: yes
  apt:
    name: vagrant
    state: installed

- name: Download and install Lando
  become: yes
  apt:
    deb: https://github.com/lando/lando/releases/download/v3.0.0-beta.35/lando-v3.0.0-beta.35.deb
